language: go

services:
  - docker
  
env:
- GO111MODULE=on

before_install:
- go build -v -o dist/book-api-service
- docker build --no-cache -t book-api-service .
- docker-compose up

script:
  - curl 127.0.0.1:8005
