language: go

services:
  - docker

before_install:
- env GO111MODULE=on go build -v -o dist/book-api-service
- docker build --no-cache -t book-api-service .
- docker compose up

script:
  - curl 127.0.0.1:5000
