version: '3.1'

services:
  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=booksdb"
      - "DB_PASS=secret"
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes: 
  data:
  